# Generated by Django 5.2.8 on 2025-12-03 16:09

import config.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('championships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(db_index=True, max_length=200)),
                ('nationality', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(blank=True, max_length=200, null=True)),
                ('racing_number', models.IntegerField(blank=True, db_index=True, null=True)),
                ('debut_year', models.IntegerField(blank=True, null=True)),
                ('total_races', models.IntegerField(default=0)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_podiums', models.IntegerField(default=0)),
                ('total_poles', models.IntegerField(default=0)),
                ('total_fastest_laps', models.IntegerField(default=0)),
                ('championships', models.IntegerField(default=0)),
                ('headshot_url', models.URLField(blank=True, null=True)),
                ('profile_image_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESERVE', 'Reserve'), ('RETIRED', 'Retired'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drivers',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='drivers_last_na_6d0279_idx'), models.Index(fields=['nationality'], name='drivers_nationa_164d0f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('base_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('headquarters', models.CharField(blank=True, max_length=200, null=True)),
                ('founded_year', models.IntegerField()),
                ('primary_color', models.CharField(blank=True, max_length=7, null=True)),
                ('secondary_color', models.CharField(blank=True, max_length=7, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_engine_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='brands.enginesupplier')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='brands.manufacturer')),
            ],
            options={
                'db_table': 'teams',
                'ordering': ['base_name'],
            },
        ),
        migrations.CreateModel(
            name='DriverSponsor',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('sponsorship_type', models.CharField(choices=[('PERSONAL', 'Personal Sponsor'), ('HELMET', 'Helmet Sponsor'), ('CLOTHING', 'Clothing Sponsor'), ('EQUIPMENT', 'Equipment Sponsor')], db_index=True, max_length=20)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_relationships', to='teams.driver')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_relationships', to='brands.sponsor')),
            ],
            options={
                'db_table': 'driver_sponsors',
                'ordering': ['-valid_from', 'driver'],
                'indexes': [models.Index(fields=['driver', 'valid_from', 'valid_until'], name='driver_spon_driver__7517b3_idx'), models.Index(fields=['sponsor', 'valid_from', 'valid_until'], name='driver_spon_sponsor_b925b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='DriverContract',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('RACE', 'Race Driver'), ('RESERVE', 'Reserve Driver'), ('TEST', 'Test Driver'), ('DEVELOPMENT', 'Development Driver'), ('LOAN', 'On Loan'), ('GUEST', 'Guest Driver')], db_index=True, max_length=20)),
                ('car_number', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('announcement_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='teams.driver')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_contracts', to='championships.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_contracts', to='teams.team')),
            ],
            options={
                'db_table': 'driver_contracts',
                'ordering': ['-season__year', 'team', 'role'],
                'indexes': [models.Index(fields=['driver', 'valid_from', 'valid_until'], name='driver_cont_driver__d878c4_idx'), models.Index(fields=['team', 'season'], name='driver_cont_team_id_6468fc_idx'), models.Index(fields=['season', 'role'], name='driver_cont_season__d7d3be_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeamIdentity',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('official_name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('primary_color', models.CharField(blank=True, max_length=7, null=True)),
                ('secondary_color', models.CharField(blank=True, max_length=7, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engine_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_identities', to='brands.enginesupplier')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_identities', to='brands.manufacturer')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_identities', to='championships.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='teams.team')),
            ],
            options={
                'db_table': 'team_identities',
                'ordering': ['-season__year', 'team'],
                'indexes': [models.Index(fields=['team', 'valid_from', 'valid_until'], name='team_identi_team_id_082ee7_idx'), models.Index(fields=['season'], name='team_identi_season__6ff824_idx')],
                'unique_together': {('team', 'season')},
            },
        ),
        migrations.CreateModel(
            name='TeamSponsor',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('sponsorship_type', models.CharField(choices=[('TITLE', 'Title Sponsor'), ('PRINCIPAL', 'Principal Partner'), ('TECHNICAL', 'Technical Partner'), ('OFFICIAL', 'Official Partner'), ('SUPPLIER', 'Official Supplier')], db_index=True, max_length=20)),
                ('is_title_sponsor', models.BooleanField(default=False)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_sponsors', to='championships.season')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_relationships', to='brands.sponsor')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_relationships', to='teams.team')),
            ],
            options={
                'db_table': 'team_sponsors',
                'ordering': ['-valid_from', 'team'],
                'indexes': [models.Index(fields=['team', 'valid_from', 'valid_until'], name='team_sponso_team_id_7dd8ca_idx'), models.Index(fields=['sponsor', 'valid_from', 'valid_until'], name='team_sponso_sponsor_d7404c_idx'), models.Index(fields=['season'], name='team_sponso_season__77e4f7_idx')],
            },
        ),
    ]
