# Generated by Django 6.0.1 on 2026-02-20 17:32

import config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="id",
            field=models.CharField(
                default=config.utils.generate_id,
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="drivercontract",
            name="id",
            field=models.CharField(
                default=config.utils.generate_id,
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="driversponsor",
            name="id",
            field=models.CharField(
                default=config.utils.generate_id,
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="id",
            field=models.CharField(
                default=config.utils.generate_id,
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="teamidentity",
            name="id",
            field=models.CharField(
                default=config.utils.generate_id,
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="teamsponsor",
            name="id",
            field=models.CharField(
                default=config.utils.generate_id,
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
