# Generated by Django 6.0.1 on 2026-02-21 15:03

import config.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_alter_driver_id_alter_drivercontract_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialHandle",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=config.utils.generate_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("TWITTER", "Twitter / X"),
                            ("INSTAGRAM", "Instagram"),
                            ("TIKTOK", "TikTok"),
                            ("YOUTUBE", "YouTube"),
                            ("FACEBOOK", "Facebook"),
                            ("LINKEDIN", "LinkedIn"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("handle", models.CharField(max_length=100)),
                ("url", models.URLField(max_length=500)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("DRIVER", "Driver"),
                            ("TEAM", "Team"),
                            ("STAFF", "Staff / Engineer / Mechanic"),
                            ("PARTNER", "Partner / Brand"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("staff_name", models.CharField(blank=True, max_length=200, null=True)),
                ("role", models.CharField(blank=True, max_length=100, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("follower_count", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="social_handles",
                        to="teams.driver",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="social_handles",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Social Handles",
                "db_table": "social_handles",
                "ordering": ["entity_type", "platform"],
                "unique_together": {("platform", "handle")},
            },
        ),
    ]
