# Generated by Django 6.0.1 on 2026-02-21 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_socialhandle"),
    ]

    operations = [
        migrations.AddField(
            model_name="drivercontract",
            name="person_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="drivercontract",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="teams.driver",
            ),
        ),
        migrations.AlterField(
            model_name="drivercontract",
            name="role",
            field=models.CharField(
                choices=[
                    ("RACE", "Race Driver"),
                    ("RESERVE", "Reserve Driver"),
                    ("TEST", "Test Driver"),
                    ("DEVELOPMENT", "Development Driver"),
                    ("LOAN", "On Loan"),
                    ("GUEST", "Guest Driver"),
                    ("TEAM_PRINCIPAL", "Team Principal"),
                    ("TECHNICAL_DIRECTOR", "Technical Director"),
                    ("RACE_ENGINEER", "Race Engineer"),
                    ("PERFORMANCE_ENGINEER", "Performance Engineer"),
                    ("HEAD_AERO", "Head of Aerodynamics"),
                    ("MECHANIC", "Mechanic"),
                    ("STAFF", "Staff (Other)"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
