# Generated by Django 5.2.8 on 2025-12-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceresult',
            name='telemetry_chart',
            field=models.ImageField(blank=True, null=True, upload_to='telemetry_charts/'),
        ),
        migrations.AddField(
            model_name='session',
            name='openf1_session_key',
            field=models.IntegerField(blank=True, help_text='Session key for OpenF1/FastF1 API', null=True),
        ),
    ]
