# Generated by Django 6.0.1 on 2026-02-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("racing", "0002_raceresult_telemetry_chart_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("ONGOING", "Ongoing"),
                    ("PROVISIONAL", "Provisional"),
                    ("COMPLETED", "Completed"),
                    ("OFFICIAL", "Official"),
                    ("CANCELLED", "Cancelled"),
                    ("POSTPONED", "Postponed"),
                ],
                db_index=True,
                default="SCHEDULED",
                max_length=20,
            ),
        ),
    ]
