# Generated by Django 5.2.8 on 2025-12-03 16:09

import config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructorStanding',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('points', models.DecimalField(decimal_places=2, max_digits=7)),
                ('wins', models.IntegerField(default=0)),
                ('podiums', models.IntegerField(default=0)),
                ('pole_positions', models.IntegerField(default=0)),
                ('fastest_laps', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'constructor_standings',
                'ordering': ['season', 'position'],
            },
        ),
        migrations.CreateModel(
            name='DriverStanding',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('points', models.DecimalField(decimal_places=2, max_digits=7)),
                ('wins', models.IntegerField(default=0)),
                ('podiums', models.IntegerField(default=0)),
                ('pole_positions', models.IntegerField(default=0)),
                ('fastest_laps', models.IntegerField(default=0)),
                ('races_entered', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'driver_standings',
                'ordering': ['season', 'position'],
            },
        ),
        migrations.CreateModel(
            name='PointsSystem',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('valid_from_year', models.IntegerField(db_index=True)),
                ('valid_until_year', models.IntegerField(blank=True, null=True)),
                ('p1_points', models.IntegerField()),
                ('p2_points', models.IntegerField()),
                ('p3_points', models.IntegerField()),
                ('p4_points', models.IntegerField()),
                ('p5_points', models.IntegerField()),
                ('p6_points', models.IntegerField()),
                ('p7_points', models.IntegerField()),
                ('p8_points', models.IntegerField()),
                ('p9_points', models.IntegerField()),
                ('p10_points', models.IntegerField()),
                ('has_fastest_lap_point', models.BooleanField(default=False)),
                ('fastest_lap_point', models.IntegerField(default=0)),
                ('fastest_lap_min_position', models.IntegerField(blank=True, null=True)),
                ('has_sprint_points', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'points_systems',
                'ordering': ['-valid_from_year'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('year', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('total_races', models.IntegerField(default=23)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'seasons',
                'ordering': ['-year'],
            },
        ),
    ]
