# Generated by Django 5.2.8 on 2025-12-03 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('championships', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructorstanding',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='teams.team'),
        ),
        migrations.AddField(
            model_name='driverstanding',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='teams.driver'),
        ),
        migrations.AddField(
            model_name='season',
            name='points_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seasons', to='championships.pointssystem'),
        ),
        migrations.AddField(
            model_name='season',
            name='tire_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seasons', to='brands.tiresupplier'),
        ),
        migrations.AddField(
            model_name='driverstanding',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_standings', to='championships.season'),
        ),
        migrations.AddField(
            model_name='constructorstanding',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructor_standings', to='championships.season'),
        ),
        migrations.AddIndex(
            model_name='driverstanding',
            index=models.Index(fields=['season', 'position'], name='driver_stan_season__5230bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='driverstanding',
            unique_together={('season', 'driver')},
        ),
        migrations.AddIndex(
            model_name='constructorstanding',
            index=models.Index(fields=['season', 'position'], name='constructor_season__32fed4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='constructorstanding',
            unique_together={('season', 'team')},
        ),
    ]
