# Generated by Django 6.0.1 on 2026-02-20 17:32

import config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("championships", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constructorstanding",
            name="id",
            field=models.CharField(
                default=config.utils.generate_id,
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="driverstanding",
            name="id",
            field=models.CharField(
                default=config.utils.generate_id,
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="pointssystem",
            name="id",
            field=models.CharField(
                default=config.utils.generate_id,
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="id",
            field=models.CharField(
                default=config.utils.generate_id,
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
