# Generated by Django 5.2.8 on 2025-12-03 16:09

import config.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('racing', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('incident_number', models.IntegerField(db_index=True)),
                ('incident_type', models.CharField(choices=[('COLLISION', 'Collision'), ('TRACK_LIMITS', 'Track Limits Violation'), ('UNSAFE_RELEASE', 'Unsafe Pit Release'), ('SPEEDING_PIT', 'Speeding in Pit Lane'), ('IGNORING_FLAGS', 'Ignoring Flags'), ('CAUSING_COLLISION', 'Causing a Collision'), ('FORCING_OFF_TRACK', 'Forcing Another Driver Off Track'), ('BLOCKING', 'Blocking/Impeding'), ('FALSE_START', 'False Start'), ('ILLEGAL_OVERTAKE', 'Illegal Overtake'), ('CAR_UNDERWEIGHT', 'Car Underweight'), ('TECHNICAL_INFRINGEMENT', 'Technical Infringement'), ('SPORTING_INFRINGEMENT', 'Sporting Infringement'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('incident_time', models.DateTimeField()),
                ('lap_number', models.IntegerField(blank=True, null=True)),
                ('track_sector', models.IntegerField(blank=True, null=True)),
                ('corner_number', models.IntegerField(blank=True, null=True)),
                ('location_description', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('video_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('NO_ACTION', 'No Action Taken'), ('NOTED', 'Noted'), ('PENALTY_ISSUED', 'Penalty Issued'), ('DISMISSED', 'Dismissed')], db_index=True, default='REPORTED', max_length=30)),
                ('reported_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('involved_drivers', models.ManyToManyField(related_name='incidents', to='teams.driver')),
                ('involved_teams', models.ManyToManyField(blank=True, related_name='incidents', to='teams.team')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='racing.session')),
            ],
            options={
                'db_table': 'incidents',
                'ordering': ['session', 'incident_number'],
            },
        ),
        migrations.CreateModel(
            name='StewardInvestigation',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('investigation_number', models.CharField(db_index=True, max_length=50)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('chief_steward', models.CharField(blank=True, max_length=200, null=True)),
                ('stewards', models.TextField(blank=True, null=True)),
                ('evidence_reviewed', models.TextField(blank=True, null=True)),
                ('hearing_held', models.BooleanField(default=False)),
                ('hearing_time', models.DateTimeField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('PENDING', 'Pending Decision'), ('NO_PENALTY', 'No Penalty'), ('REPRIMAND', 'Reprimand'), ('WARNING', 'Warning'), ('FINE', 'Fine'), ('TIME_PENALTY', 'Time Penalty'), ('GRID_PENALTY', 'Grid Penalty'), ('DRIVE_THROUGH', 'Drive-Through Penalty'), ('STOP_GO', 'Stop-Go Penalty'), ('DISQUALIFICATION', 'Disqualification'), ('POINTS_PENALTY', 'License Points Penalty')], db_index=True, default='PENDING', max_length=30)),
                ('decision_time', models.DateTimeField(blank=True, null=True)),
                ('decision_document_url', models.URLField(blank=True, null=True)),
                ('reasoning', models.TextField(blank=True, null=True)),
                ('appeal_status', models.CharField(choices=[('NOT_APPEALED', 'Not Appealed'), ('APPEAL_PENDING', 'Appeal Pending'), ('APPEAL_UPHELD', 'Appeal Upheld'), ('APPEAL_REJECTED', 'Appeal Rejected'), ('APPEAL_WITHDRAWN', 'Appeal Withdrawn')], default='NOT_APPEALED', max_length=30)),
                ('appeal_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('appeal_decided_at', models.DateTimeField(blank=True, null=True)),
                ('appeal_reasoning', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='stewards.incident')),
                ('investigated_drivers', models.ManyToManyField(related_name='steward_investigations', to='teams.driver')),
                ('investigated_teams', models.ManyToManyField(blank=True, related_name='steward_investigations', to='teams.team')),
            ],
            options={
                'db_table': 'steward_investigations',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('penalty_type', models.CharField(choices=[('REPRIMAND', 'Reprimand'), ('WARNING', 'Warning'), ('FINE', 'Fine'), ('TIME_5S', '5 Second Time Penalty'), ('TIME_10S', '10 Second Time Penalty'), ('TIME_30S', '30 Second Time Penalty'), ('GRID_3', '3 Place Grid Penalty'), ('GRID_5', '5 Place Grid Penalty'), ('GRID_10', '10 Place Grid Penalty'), ('GRID_BACK', 'Back of Grid'), ('GRID_PIT_LANE', 'Pit Lane Start'), ('DRIVE_THROUGH', 'Drive-Through Penalty'), ('STOP_GO_10S', '10s Stop-Go Penalty'), ('POINTS_DEDUCTION', 'Championship Points Deduction'), ('LICENSE_POINTS', 'License Points'), ('DISQUALIFICATION', 'Disqualification'), ('RACE_BAN', 'Race Ban')], db_index=True, max_length=30)),
                ('penalty_value', models.IntegerField(blank=True, null=True)),
                ('fine_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('license_points', models.IntegerField(blank=True, null=True)),
                ('issued_at', models.DateTimeField()),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SERVED', 'Served'), ('APPLIED', 'Applied'), ('CARRIED_OVER', 'Carried Over'), ('SUSPENDED', 'Suspended'), ('RESCINDED', 'Rescinded')], db_index=True, default='PENDING', max_length=20)),
                ('infringement', models.TextField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('document_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_to_race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties_applied', to='racing.race')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='teams.driver')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties', to='stewards.incident')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='racing.session')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='teams.team')),
                ('investigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties', to='stewards.stewardinvestigation')),
            ],
            options={
                'db_table': 'penalties',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['session', 'incident_time'], name='incidents_session_221317_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['incident_type'], name='incidents_inciden_994021_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status'], name='incidents_status_9db31b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='incident',
            unique_together={('session', 'incident_number')},
        ),
        migrations.AddIndex(
            model_name='stewardinvestigation',
            index=models.Index(fields=['investigation_number'], name='steward_inv_investi_2812f1_idx'),
        ),
        migrations.AddIndex(
            model_name='stewardinvestigation',
            index=models.Index(fields=['decision'], name='steward_inv_decisio_6b8a9f_idx'),
        ),
        migrations.AddIndex(
            model_name='stewardinvestigation',
            index=models.Index(fields=['opened_at'], name='steward_inv_opened__003d0f_idx'),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['driver', 'issued_at'], name='penalties_driver__3f73d5_idx'),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['team', 'issued_at'], name='penalties_team_id_2bb67e_idx'),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['penalty_type'], name='penalties_penalty_5c2ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['status'], name='penalties_status_2c0e89_idx'),
        ),
    ]
