# Generated by Django 5.2.8 on 2025-12-03 16:10

import config.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circuits', '0001_initial'),
        ('racing', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('original_lang', models.CharField(max_length=10)),
                ('original_title', models.CharField(max_length=500)),
                ('original_slug', models.SlugField(max_length=200)),
                ('original_body', models.TextField()),
                ('original_summary', models.TextField(blank=True, null=True)),
                ('original_url', models.URLField(max_length=1000)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('featured_image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('NORMAL', 'Normal'), ('LOW', 'Low')], db_index=True, default='NORMAL', max_length=20)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'News Categories',
                'db_table': 'news_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('feed_url', models.URLField(max_length=500)),
                ('lang', models.CharField(default='en', max_length=10)),
                ('priority', models.IntegerField(default=50)),
                ('fetch_interval', models.IntegerField(default=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sources',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArticleCircuit',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article')),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circuits.circuit')),
            ],
            options={
                'db_table': 'article_circuits',
                'unique_together': {('article', 'circuit')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='circuits',
            field=models.ManyToManyField(blank=True, related_name='news_articles', through='news.ArticleCircuit', to='circuits.circuit'),
        ),
        migrations.CreateModel(
            name='ArticleDriver',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.driver')),
            ],
            options={
                'db_table': 'article_drivers',
                'unique_together': {('article', 'driver')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='drivers',
            field=models.ManyToManyField(blank=True, related_name='news_articles', through='news.ArticleDriver', to='teams.driver'),
        ),
        migrations.CreateModel(
            name='ArticleRace',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing.race')),
            ],
            options={
                'db_table': 'article_races',
                'unique_together': {('article', 'race')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='races',
            field=models.ManyToManyField(blank=True, related_name='news_articles', through='news.ArticleRace', to='racing.race'),
        ),
        migrations.CreateModel(
            name='ArticleTeam',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'db_table': 'article_teams',
                'unique_together': {('article', 'team')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='news_articles', through='news.ArticleTeam', to='teams.team'),
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newscategory')),
            ],
            options={
                'db_table': 'article_categories',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(related_name='articles', through='news.ArticleCategory', to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.source'),
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.tag')),
            ],
            options={
                'db_table': 'article_tags',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', through='news.ArticleTag', to='news.tag'),
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('lang', models.CharField(db_index=True, max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=200)),
                ('body', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEWED', 'Reviewed'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('translator', models.CharField(blank=True, max_length=100, null=True)),
                ('translated_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='news.article')),
            ],
            options={
                'db_table': 'translations',
                'ordering': ['article', 'lang'],
            },
        ),
        migrations.AddIndex(
            model_name='articlecategory',
            index=models.Index(fields=['article', 'is_primary'], name='article_cat_article_6841c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='articlecategory',
            unique_together={('article', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='articletag',
            unique_together={('article', 'tag')},
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published_at', 'is_published'], name='articles_publish_8c0630_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['source', '-published_at'], name='articles_source__94fb86_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['priority', '-published_at'], name='articles_priorit_50b438_idx'),
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['lang', 'status'], name='translation_lang_1297f1_idx'),
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['slug', 'lang'], name='translation_slug_e4dac1_idx'),
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['article', 'lang'], name='translation_article_25b180_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('article', 'lang')},
        ),
    ]
