# Generated by Django 5.2.8 on 2025-12-04 09:30

import config.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleChunk',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('sequence', models.IntegerField(help_text='Order of the chunk in the article')),
                ('content', models.TextField()),
                ('chunk_type', models.CharField(choices=[('HEADING', 'Heading'), ('PARAGRAPH', 'Paragraph'), ('LIST', 'List'), ('QUOTE', 'Quote'), ('IMAGE', 'Image'), ('OTHER', 'Other')], default='PARAGRAPH', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='news.article')),
            ],
            options={
                'db_table': 'article_chunks',
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['article', 'sequence'], name='article_chu_article_668762_idx')],
            },
        ),
    ]
