# Generated by Django 5.2.8 on 2025-12-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_articlechunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_duplicate',
            field=models.BooleanField(db_index=True, default=False, help_text='Is this a duplicate of another article?'),
        ),
        migrations.AddField(
            model_name='article',
            name='quality_score',
            field=models.FloatField(db_index=True, default=0.0, help_text='Content quality score 0.0-100.0'),
        ),
    ]
