# Generated by Django 5.2.8 on 2025-12-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_is_duplicate_article_quality_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='simhash',
            field=models.CharField(blank=True, db_index=True, help_text='64-bit SimHash fingerprint for deduplication', max_length=64, null=True),
        ),
    ]
