# Generated by Django 6.0.1 on 2026-02-20 11:38

import config.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_article_simhash"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsCategoryTranslation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=config.utils.generate_id,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lang", models.CharField(db_index=True, max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="news.newscategory",
                    ),
                ),
            ],
            options={
                "db_table": "news_category_translations",
                "unique_together": {("category", "lang")},
            },
        ),
    ]
