# Generated by Django 6.0.1 on 2026-02-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_alter_article_external_id_alter_article_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="ingestion_status",
            field=models.CharField(
                choices=[
                    ("INGESTED", "Ingested"),
                    ("PROCESSED", "Processed"),
                    ("PUBLISHED", "Published"),
                    ("LOW_QUALITY", "Low Quality"),
                    ("DUPLICATE", "Duplicate"),
                ],
                db_index=True,
                default="INGESTED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="consecutive_errors",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="source",
            name="is_healthy",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="source",
            name="last_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="source",
            name="last_success_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="source",
            name="total_articles_fetched",
            field=models.IntegerField(default=0),
        ),
    ]
