# Generated by Django 6.0.1 on 2026-02-26 18:35

from django.db import migrations


def backfill_ingestion_status(apps, schema_editor):
    Article = apps.get_model('news', 'Article')
    # Duplicates
    Article.objects.filter(is_duplicate=True).update(ingestion_status='DUPLICATE')
    # Published quality (>= 50)
    Article.objects.filter(is_duplicate=False, quality_score__gte=50).update(ingestion_status='PUBLISHED')
    # Processed quality (30 <= score < 50)
    Article.objects.filter(
        is_duplicate=False, quality_score__gte=30, quality_score__lt=50
    ).update(ingestion_status='PROCESSED')
    # Low quality (score < 30, includes unprocessed quality_score=0)
    Article.objects.filter(is_duplicate=False, quality_score__lt=30).update(ingestion_status='LOW_QUALITY')


def reverse_backfill(apps, schema_editor):
    apps.get_model('news', 'Article').objects.all().update(ingestion_status='INGESTED')


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_article_ingestion_status_source_consecutive_errors_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_ingestion_status, reverse_code=reverse_backfill),
    ]
