# Generated by Django 5.2.8 on 2025-12-03 16:09

import config.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('championships', '0002_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('full_name', models.CharField(blank=True, max_length=300, null=True)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('circuit_type', models.CharField(choices=[('PERMANENT', 'Permanent Race Circuit'), ('STREET', 'Street Circuit'), ('SEMI_PERMANENT', 'Semi-Permanent Circuit')], default='PERMANENT', max_length=20)),
                ('direction', models.CharField(blank=True, max_length=20, null=True)),
                ('opened_year', models.IntegerField(blank=True, null=True)),
                ('current_length_km', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('current_corners', models.IntegerField(blank=True, null=True)),
                ('current_drs_zones', models.IntegerField(blank=True, null=True)),
                ('track_map_url', models.URLField(blank=True, null=True)),
                ('aerial_image_url', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'circuits',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['country', 'name'], name='circuits_country_c50996_idx')],
            },
        ),
        migrations.CreateModel(
            name='CircuitConfiguration',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('layout_name', models.CharField(blank=True, max_length=200, null=True)),
                ('length_km', models.DecimalField(decimal_places=3, max_digits=6)),
                ('corners', models.IntegerField()),
                ('left_corners', models.IntegerField(blank=True, null=True)),
                ('right_corners', models.IntegerField(blank=True, null=True)),
                ('drs_zones', models.IntegerField(default=0)),
                ('lap_record_time', models.CharField(blank=True, max_length=20, null=True)),
                ('lap_record_year', models.IntegerField(blank=True, null=True)),
                ('longest_straight_m', models.IntegerField(blank=True, null=True)),
                ('elevation_change_m', models.IntegerField(blank=True, null=True)),
                ('pit_lane_length_m', models.IntegerField(blank=True, null=True)),
                ('pit_speed_limit_kph', models.IntegerField(blank=True, null=True)),
                ('track_map_url', models.URLField(blank=True, null=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='circuits.circuit')),
                ('lap_record_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circuit_lap_records', to='teams.driver')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circuit_configurations', to='championships.season')),
            ],
            options={
                'db_table': 'circuit_configurations',
                'ordering': ['-season__year', 'circuit'],
                'indexes': [models.Index(fields=['circuit', 'valid_from', 'valid_until'], name='circuit_con_circuit_1872c2_idx'), models.Index(fields=['season'], name='circuit_con_season__d9d4c7_idx')],
                'unique_together': {('circuit', 'season')},
            },
        ),
    ]
