# Generated by Django 5.2.8 on 2025-12-03 16:09

import config.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentSupplier',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('BRAKE', 'Brake System'), ('FUEL', 'Fuel'), ('LUBRICANT', 'Lubricant'), ('HYDRAULIC', 'Hydraulic System'), ('ELECTRONICS', 'Electronics'), ('SUSPENSION', 'Suspension')], db_index=True, max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'component_suppliers',
                'ordering': ['component_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('founded_year', models.IntegerField()),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'manufacturers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sponsors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TireSupplier',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tire_suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EngineSupplier',
            fields=[
                ('id', models.CharField(default=config.utils.generate_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brands.manufacturer')),
            ],
            options={
                'db_table': 'engine_suppliers',
                'ordering': ['name'],
            },
        ),
    ]
